/*ENDER PEARL COOL DOWN MADE BY @PIZZAHAET, @DERPIFIC, AND @EVADEZOREX
* Defualt cool down time for Minecraft vanilla is 1 second I recomend not going over 60 seconds due to possible glitches and damage to
* your server we developers of this plugin and the Mojang team are not responsible to any harm to your server
* GNU HERE
*/
EnderPearl-CoolDown: 1
