# ENDER PEARL COOL DOWN MADE BY @PIZZAHAET, @DERPIFIC, AND @EVADEZOREX.
# Defualt cooldown time for vanilla Minecraft is 1 second, I recommend not going over 60 seconds due to possible glitches and damage to
# your server, we developers of this plugin and the Mojang team are not responsible to any harm to your server.

EnderPearl-CoolDown: 1
